#!/usr/bin/env bash
# comment

for pid in $(ls /proc | grep -E '^[0-9]+$'); do
    cmd=$(tr '\0' ' ' < /proc/$pid/cmdline 2>/dev/null)
    if echo "$cmd" | grep -q "7-highlander"; then
        kill "$pid"
    fi
done
