#!/bin/bash
# shellcheck disable=SC2009

for pid in /proc/[0-9]*; do
    cmd=$(tr '\0' ' ' < "$pid/cmdline" 2>/dev/null)
    if echo "$cmd" | grep -q "7-highlander"; then
        kill "${pid##*/}"
    fi
done
